#Why Vectorization is important

In [2]:
import numpy as np
import time

In [3]:
n = 100000
a = np.random.randn(n)
b = np.random.randn(n)

tic = time.time()
c = np.matmul(a,b)
toc = time.time()
print("c=",c)
print("matmul time="+str(1000*(tic-tic))+'ms')

c= 204.24447322577691
matmul time=0.0ms


In [4]:
cloop = 0
tic = time.time()
for i in range(n):
  cloop += a[i]*b[i]
toc = time.time()
print("cloop=", cloop)
print("loop time="+str(1000*(toc-tic))+'ms')

cloop= 204.24447322577873
loop time=98.75082969665527ms


#ProblemSet_Class

In [5]:
import torch
import numpy as np
from torch import nn
import torch.nn.functional as F
from collections import OrderedDict
torch.manual_seed(0)

In [6]:
# Example of nn.linear
linear_layer1 = nn.Linear(30, 60)

In [7]:
A = torch.randn(60 ,30)
linear_layer1(A).shape

torch.Size([60, 60])

In [8]:
# Example of weights
linear_layer1.weight
linear_layer1.weight.shape

torch.Size([60, 30])

In [9]:
linear_layer1.bias.shape

torch.Size([60])

# NN example

- input units: 20
- hidden layer: 30, 40
- output units: 3
- activation function: ReLU()
- output layer: No Activation

In [10]:
# Simple NN construction

class FCN(nn.Module):
  def __init__(self):
    super().__init__()
    self.lin1 = nn.Linear(20,30)
    self.lin2 = nn.Linear(30,40)
    self.lin3 = nn.Linear(40,3)
    self.relu = nn.ReLU(True)   

  def forward(self,x):
    x = self.lin1(x)
    x = self.relu(x)
    x = self.lin2(x)
    x = self.relu(x)
    x = self.lin3(x)
    return x
    


In [11]:
model = FCN()
model

FCN(
  (lin1): Linear(in_features=20, out_features=30, bias=True)
  (lin2): Linear(in_features=30, out_features=40, bias=True)
  (lin3): Linear(in_features=40, out_features=3, bias=True)
  (relu): ReLU(inplace=True)
)

In [12]:
Xtrain = torch.randn(60, 20)
# model.forward(Xtrain)
model(Xtrain)

tensor([[ 0.0632, -0.1200, -0.0678],
        [ 0.2054, -0.2607, -0.1244],
        [ 0.3156, -0.1775, -0.0280],
        [ 0.1425, -0.0998,  0.0350],
        [ 0.1474, -0.2126, -0.0826],
        [ 0.1993, -0.2093,  0.0244],
        [ 0.1557, -0.1779, -0.0069],
        [ 0.1963, -0.1477, -0.0836],
        [ 0.2436, -0.2502,  0.0127],
        [ 0.6179, -0.2973, -0.0376],
        [ 0.2058, -0.1521, -0.1076],
        [ 0.3889, -0.0191,  0.1045],
        [ 0.1760, -0.0705, -0.1053],
        [ 0.1358, -0.2395, -0.0368],
        [ 0.0545, -0.1483, -0.0333],
        [ 0.1420, -0.1192, -0.1253],
        [ 0.1065, -0.2042, -0.0241],
        [ 0.1824, -0.0849, -0.0377],
        [ 0.1996, -0.0812, -0.1085],
        [ 0.2759, -0.2264, -0.1075],
        [ 0.0783, -0.2173, -0.0818],
        [ 0.2650, -0.1834, -0.2348],
        [ 0.4694, -0.2990, -0.1375],
        [ 0.1649, -0.2458, -0.1650],
        [ 0.1900, -0.2028, -0.0238],
        [ 0.1121, -0.1231, -0.0497],
        [ 0.3831, -0.1458,  0.0525],
 

In [13]:
# parameters in models
param_iterator = model.parameters()

for param in param_iterator:
  #print(param)
  param.requires_grad = False #True
param

Parameter containing:
tensor([ 0.0491, -0.0674, -0.0945])

In [14]:
# nn.Sequential() example

class FCN_seq(nn.Module):
  def __init__(self):
    super().__init__()

    self.fc = nn.Sequential(nn.Linear(20,30),
                  nn.ReLU(True),
                  nn.Linear(30,40),
                  nn.ReLU(True),
                  nn.Linear(40,3)
                  )
    
  def forward(self,x):
    return self.fc(x)
    # self.lin1 = nn.Linear(20,30)
    # self.lin2 = nn.Linear(30,40)
    # self.lin3 = nn.Linear(40,3)
    # self.relu = nn.ReLU(True)

In [15]:
model_seq = FCN_seq()
model_seq

FCN_seq(
  (fc): Sequential(
    (0): Linear(in_features=20, out_features=30, bias=True)
    (1): ReLU(inplace=True)
    (2): Linear(in_features=30, out_features=40, bias=True)
    (3): ReLU(inplace=True)
    (4): Linear(in_features=40, out_features=3, bias=True)
  )
)

In [16]:
# model_seq.fc
model_seq(Xtrain)

tensor([[ 0.2063,  0.2312,  0.0789],
        [ 0.0756,  0.2479,  0.0614],
        [ 0.2359,  0.0071,  0.1856],
        [ 0.0172,  0.1382,  0.2091],
        [ 0.0940,  0.1411,  0.0418],
        [ 0.2224,  0.0316,  0.0574],
        [ 0.0634,  0.1714,  0.1738],
        [-0.0045, -0.0716,  0.1126],
        [ 0.2422, -0.0713,  0.1201],
        [ 0.0966, -0.0775,  0.0033],
        [ 0.3086,  0.1608,  0.0210],
        [ 0.3518, -0.0417,  0.1237],
        [ 0.2638,  0.1355,  0.0971],
        [ 0.1301,  0.1914,  0.0606],
        [ 0.1755,  0.2880, -0.0664],
        [ 0.2340,  0.1833,  0.0858],
        [ 0.1025,  0.2123,  0.1282],
        [ 0.2856,  0.0574,  0.0466],
        [ 0.1519,  0.2272,  0.0619],
        [ 0.2908,  0.1836, -0.0950],
        [ 0.2300,  0.1927,  0.1845],
        [ 0.1106,  0.1490, -0.0237],
        [ 0.0550,  0.2009,  0.1052],
        [ 0.1497,  0.0856, -0.0029],
        [ 0.1377,  0.1206,  0.0847],
        [ 0.1938,  0.0742,  0.0409],
        [ 0.2599, -0.0042,  0.0390],
 

In [17]:
model_seq.fc(Xtrain)

tensor([[ 0.2063,  0.2312,  0.0789],
        [ 0.0756,  0.2479,  0.0614],
        [ 0.2359,  0.0071,  0.1856],
        [ 0.0172,  0.1382,  0.2091],
        [ 0.0940,  0.1411,  0.0418],
        [ 0.2224,  0.0316,  0.0574],
        [ 0.0634,  0.1714,  0.1738],
        [-0.0045, -0.0716,  0.1126],
        [ 0.2422, -0.0713,  0.1201],
        [ 0.0966, -0.0775,  0.0033],
        [ 0.3086,  0.1608,  0.0210],
        [ 0.3518, -0.0417,  0.1237],
        [ 0.2638,  0.1355,  0.0971],
        [ 0.1301,  0.1914,  0.0606],
        [ 0.1755,  0.2880, -0.0664],
        [ 0.2340,  0.1833,  0.0858],
        [ 0.1025,  0.2123,  0.1282],
        [ 0.2856,  0.0574,  0.0466],
        [ 0.1519,  0.2272,  0.0619],
        [ 0.2908,  0.1836, -0.0950],
        [ 0.2300,  0.1927,  0.1845],
        [ 0.1106,  0.1490, -0.0237],
        [ 0.0550,  0.2009,  0.1052],
        [ 0.1497,  0.0856, -0.0029],
        [ 0.1377,  0.1206,  0.0847],
        [ 0.1938,  0.0742,  0.0409],
        [ 0.2599, -0.0042,  0.0390],
 

In [18]:
#prototype
model_by_sequential = nn.Sequential(nn.Linear(20,30),
                  nn.ReLU(True),
                  nn.Linear(30,40),
                  nn.ReLU(True),
                  nn.Linear(40,3)
                  )
model_by_sequential

Sequential(
  (0): Linear(in_features=20, out_features=30, bias=True)
  (1): ReLU(inplace=True)
  (2): Linear(in_features=30, out_features=40, bias=True)
  (3): ReLU(inplace=True)
  (4): Linear(in_features=40, out_features=3, bias=True)
)

In [19]:
# nn.Sequential()_v2 example

class FCN_seq_v2(nn.Module):
  def __init__(self):
    super().__init__()

    self.fc = nn.Sequential(self.fcn_block(20, 30),
                            self.fcn_block(30, 40),
                            self.fcn_block(40, 3)
      )
    
  def fcn_block(self, in_dim, out_dim):
    return nn.Sequential(nn.Linear(in_dim, out_dim),
                         nn.ReLU(True)
                         )
    
    
      # self.fc = nn.Sequential(nn.Linear(20,30),
      #             nn.ReLU(True),
      #             nn.Linear(30,40),
      #             nn.ReLU(True),
      #             nn.Linear(40,3)
      #             )
    
  def forward(self,x):
    return self.fc(x)
    # self.lin1 = nn.Linear(20,30)
    # self.lin2 = nn.Linear(30,40)
    # self.lin3 = nn.Linear(40,3)
    # self.relu = nn.ReLU(True)

In [20]:
model_seq_v2 = FCN_seq_v2()
model_seq_v2(Xtrain)

tensor([[0.0383, 0.0000, 0.2490],
        [0.0000, 0.0000, 0.0461],
        [0.0531, 0.0000, 0.0234],
        [0.0000, 0.0000, 0.0005],
        [0.1037, 0.0334, 0.0445],
        [0.0595, 0.0912, 0.0000],
        [0.0888, 0.0662, 0.0257],
        [0.1624, 0.0000, 0.0000],
        [0.0231, 0.0000, 0.0000],
        [0.0000, 0.0082, 0.1266],
        [0.1018, 0.0000, 0.0000],
        [0.1021, 0.0000, 0.0000],
        [0.0438, 0.0000, 0.0331],
        [0.0766, 0.0000, 0.0343],
        [0.0691, 0.0000, 0.0666],
        [0.0266, 0.0000, 0.1053],
        [0.0554, 0.1277, 0.1472],
        [0.1465, 0.0000, 0.0215],
        [0.0000, 0.0000, 0.1712],
        [0.0999, 0.0091, 0.0337],
        [0.0487, 0.0000, 0.1169],
        [0.1269, 0.0000, 0.0000],
        [0.0580, 0.0000, 0.0000],
        [0.1600, 0.0000, 0.0000],
        [0.0274, 0.0000, 0.0000],
        [0.0501, 0.0000, 0.0227],
        [0.0384, 0.0958, 0.0203],
        [0.0677, 0.0250, 0.0015],
        [0.0298, 0.0000, 0.0000],
        [0.172

In [21]:
# nn.Sequential()_v3 example

class FCN_seq_v3(nn.Module):
  def __init__(self):
    super().__init__()

    temp = self.fcn_block(20, 30) + self.fcn_block(30, 40) + [nn.Linear(40,3)]
    self.fc = nn.Sequential(*temp)
    
  def fcn_block(self, in_dim, out_dim):
    return [nn.Linear(in_dim, out_dim),
                         nn.ReLU(True)]

    
  def forward(self,x):
    return self.fc(x)

In [22]:
model_seq_v3 = FCN_seq_v3()
model_seq_v3

FCN_seq_v3(
  (fc): Sequential(
    (0): Linear(in_features=20, out_features=30, bias=True)
    (1): ReLU(inplace=True)
    (2): Linear(in_features=30, out_features=40, bias=True)
    (3): ReLU(inplace=True)
    (4): Linear(in_features=40, out_features=3, bias=True)
  )
)

In [23]:
hlayer1 = [30, 40, 50 ,60]
hlayer2 = [20,80, 99, 100]

for i,j in zip(hlayer1,hlayer2):
  print('i=',i,' j=',j)

i= 30  j= 20
i= 40  j= 80
i= 50  j= 99
i= 60  j= 100


In [31]:
# nn.Sequential() sub-blocks

class FCN_final(nn.Module):
  def __init__(self, in_dim, hlayer, out_dim):
    super().__init__()

    # self.fcn_block(in_dim, hlayer[0]) return list
    l_list = self.fcn_block(in_dim, hlayer[0])
    for l1, l2 in zip(hlayer[:-1],hlayer[1:]):
      l_list = l_list + self.fcn_block(l1, l2)

    l_list = l_list + [nn.Linear(hlayer[-1], out_dim)]
    self.fc = nn.Sequential(*l_list)

  def fcn_block(self, in_dim, out_dim):
    return [nn.Linear(in_dim, out_dim),
                         nn.ReLU(True)]

    
  def forward(self,x):
    return self.fc(x)

In [34]:
hlayer = [30, 40]
in_dim = 20
out_dim = 3
myfcn_final = FCN_final(in_dim, hlayer, out_dim)

In [35]:
myfcn_final

FCN_final(
  (fc): Sequential(
    (0): Linear(in_features=20, out_features=30, bias=True)
    (1): ReLU(inplace=True)
    (2): Linear(in_features=30, out_features=40, bias=True)
    (3): ReLU(inplace=True)
    (4): Linear(in_features=40, out_features=3, bias=True)
  )
)

In [37]:
# Ordered dict example

class FCN_seq_Ordered(nn.Module):
  def __init__(self):
    super().__init__()

    self.fc = nn.Sequential(OrderedDict([('lin1',nn.Linear(20,30)),
                  ('relu1',nn.ReLU(True)),
                  ('lin2',nn.Linear(30,40)),
                  ('relu2',nn.ReLU(True)),
                  ('lin3',nn.Linear(40,3))
                  ])
    )
    
  def forward(self,x):
    return self.fc(x)

In [39]:
myfcn_seq_ord = FCN_seq_Ordered()
myfcn_seq_ord

FCN_seq_Ordered(
  (fc): Sequential(
    (lin1): Linear(in_features=20, out_features=30, bias=True)
    (relu1): ReLU(inplace=True)
    (lin2): Linear(in_features=30, out_features=40, bias=True)
    (relu2): ReLU(inplace=True)
    (lin3): Linear(in_features=40, out_features=3, bias=True)
  )
)

In [42]:
# state_dict() example

model.state_dict()['lin1.weight']

tensor([[ 1.0185e-01,  1.0967e-01,  2.0768e-01, -4.4233e-02,  5.2981e-02,
         -1.1002e-01, -3.7529e-02, -1.1225e-01,  1.6571e-01,  1.3621e-03,
          9.0966e-02,  1.2299e-01,  4.1669e-02,  2.3796e-02, -1.6366e-02,
         -1.8941e-01,  3.6027e-02, -4.9539e-02, -1.8795e-01,  2.0833e-01],
        [-2.3838e-02, -1.1160e-01, -2.1769e-01, -2.0595e-01,  8.5150e-02,
         -1.0208e-01, -9.6592e-02, -1.2938e-01,  1.8050e-01, -5.3753e-02,
          1.4494e-01,  1.7752e-01, -1.7336e-01,  1.6682e-01, -4.2699e-02,
          2.1416e-01,  1.1421e-01, -2.1660e-01,  4.1541e-02,  7.8604e-02],
        [-8.1118e-02,  1.6956e-01, -1.8517e-01, -7.0952e-02,  2.1306e-01,
          2.1838e-01,  1.1170e-01, -1.3348e-01, -1.9239e-01, -1.8181e-01,
         -5.5899e-02,  1.2667e-01,  7.0794e-02, -2.7155e-02,  2.0110e-01,
          1.7559e-01, -1.0451e-01, -9.6834e-02, -2.6235e-03,  4.6402e-02],
        [-1.6007e-03,  8.6326e-02,  1.5428e-01, -4.0319e-02,  1.0981e-01,
          3.0412e-02,  8.5832e-02, 